name: airbyte-ci-teradata-ci
on:
  push:
    branches:
      - td_develop
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  teradata-tests:
    name: "Run Airbyte Teradata Destination Connector Unit and Integration Tests"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v4
        with:
          ref: ${{ vars.BRANCH_NAME }}
          persist-credentials: false
      - name: Print Java version and env
        run: |
          java -version
          echo "ForkJoinPool parallelism: $JAVA_TOOL_OPTIONS"
          env
