name: airbyte-ci-teradata-master-sync-with-parent-master
on:
  schedule:
    - cron: '30 20,2 * * *' # At every 20.30 (8.30 PM) and 2.30 AM UTC timezone - 12.00 AM IST and 8 AM
  workflow_dispatch: # on button click
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Teradata Airbyte Repo
         uses: actions/checkout@v4
         with:
          repository: Teradata/airbyte
          ref: master
          persist-credentials: false
        
       - name: Add Airbyte Upstream and Fetch
         run: |
            git remote add airbyte-upstream https://github.com/airbytehq/airbyte.git
            git fetch airbyte-upstream master
        
       - name: Configure Git
         run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
        
       - name: Merge Airbyte master into Teradata master
         run: |
            git merge --no-ff --no-edit airbyte-upstream/master
        
       - name: Push merged changes to Teradata master
         run: |
            git push origin master

