name: airbyte-ci-master-sync-with-parent-master
on:
  schedule:
    - cron: '30 20,2 * * *' # At every 20.30 (8.30 PM) and 2.30 AM UTC timezone - 12.00 AM IST and 8 AM
  workflow_dispatch: # on button click
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Airbyte Repo
         run: |
          rm -rf airbyte-repo 
          git clone --branch master https://github.com/airbytehq/airbyte.git airbyte-repo
          cd airbyte-repo
       - name: Configure Git
         run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
       - name: Update master from Airbyte master repo
         run: |
          cd airbyte-repo
          git remote add teradata-repo https://github.com/Teradata/airbyte.git
          git push teradata-repo master:master --force
          cd ..
          rm -rf airbyte-repo
